name: build
on: [ pull_request, push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build Fabric
        run: ./gradlew fabric:build
      - name: Build NeoForge
        run: ./gradlew neoforge:build
      - name: Get commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NeoTM-${{ steps.vars.outputs.sha_short }}
          path: build/release/
